Accept null playback controls when Alexa sings
The MediaSession is not being updated when Alexa sings.

This is because Moshi crashes when trying to parse
the RenderPlayerInfo.

error: com.squareup.moshi.JsonDataException:
Non-null value 'controls' was null at $.payload.control

AACS expects the 'controls' field of the RenderPlayerInfo
object to be non nullable but this is not the case
when Alexa sings.

{
    "audioItemId": "",
    "content": {
        "art": {
            "contentDescription": "Take Me Out to the Ball Game",
            "sources": [{
                "heightPixels": 0,
                "size": null,
                "url": "https:\/\/d3l071etx9fo2i.cloudfront.net...",
                "widthPixels": 0
            }]
        },
        "background": null,
        "header": null,
        "headerSubtext1": null,
        "mediaLengthInMilliseconds": 0,
        "provider": {
            "logo": {
                "contentDescription": null,
                "sources": [{
                    "heightPixels": null,
                    "size": null,
                    "url": "https:\/\/s3.amazonaws.com\/CAPS-...",
                    "widthPixels": null
                }]
            },
            "name": "Greetings"
        },
        "title": "Take Me Out to the Ball Game",
        "titleSubtext1": "Alexa",
        "titleSubtext2": "Greetings"
    },
    "controls": null
}

Signed-off-by: Rafael Chagas <rafael.chagas@volvo.com>